flowchart LR
  Power["USB / power bank"] --> ESP32["ESP32"]
  ESP32_GPIO5["ESP32 GPIO5"] --> ULN_IN1["ULN2003 IN1"]
  ESP32_GPIO18["ESP32 GPIO18"] --> ULN_IN2["ULN2003 IN2"]
  ESP32_GPIO19["ESP32 GPIO19"] --> ULN_IN3["ULN2003 IN3"]
  ESP32_GPIO21["ESP32 GPIO21"] --> ULN_IN4["ULN2003 IN4"]
  ESP32_VIN["ESP32 VIN"] --> ULN_PLUS["ULN2003 +"]
  ESP32_GND["ESP32 GND"] --> ULN_MINUS["ULN2003 -"]
  ULN_SOCKET["ULN2003 white socket"] --> MOTOR["28BYJ-48 5-wire motor plug"]
